In [ ]:
import os
path = 'c://Users/HN34064/Downloads'
downloaded_files = os.listdir(path)
#downloaded_files_flag = list(map(lambda x: str(x).endswith('.csv'), downloaded_files))
downloaded_files = list(filter(lambda x: str(x).endswith('.csv'),downloaded_files))

['20251031.csv',
 '20251130.csv',
 '509e19c4-09d1-4f3d-9ec4-f7a6e874bb78.csv',
 'airlines_final.csv',
 'banking_dirty (1).csv',
 'banking_dirty.csv',
 'Cartera 2025-06-30.csv',
 'CarteraCDR_dic24_ago25.csv',
 'cartera_crediticia_2025-08-31.csv',
 'CLEANED_DATASET_ORIGINACIONES_FINAL.csv',
 'CNBS.csv',
 'dataset_2026-01-26T18_53_29.952756999Z_DEFAULT_INTEGRATION_IMF.RES_WEO_9.0.0.csv',
 'dataset_2026-03-19T21_48_10.215546145Z_DEFAULT_INTEGRATION_IMF.RES_WEO_9.0.0.csv',
 'Dataset_originacion.csv',
 'Dataset_originacion_HN.csv',
 'datos_entrenamiento.csv',
 'gerson_archivo_31072023.csv',
 'GT_VARIABLES_EXPLICATIVAS_SEPT_2023_TRA20v2.csv',
 'HND_Data_Sum.csv',
 'HND_MATRIZ_FINAL_MARKOV_202406.csv',
 'ind_.csv',
 'pronostico_remesas_2025-07_a_2028-12.csv',
 'restaurants_L2.csv',
 'restaurants_L2_dirty.csv',
 'ride_sharing_new.csv',
 'tc_estimado_2028_12(Proyección).csv']

In [31]:
file_names = [ 'restaurants_L2_dirty.csv','restaurants_L2.csv','banking_dirty (1).csv',
'airlines_final.csv', 'ride_sharing_new.csv','banking_dirty.csv']

In [98]:
import pandas as pd
from thefuzz import process

df = pd.read_csv(path+'/'+file_names[0], index_col=0)
df['type'].value_counts()
#df

type
american            20
italian              7
californian          5
coffee shops         5
asian                4
hot dogs             3
diners               3
delis                3
hamburgers           3
mexican              3
noodle shops         2
pacific new wave     2
seafood              2
continental          1
coffeebar            1
eclectic             1
desserts             1
chinese              1
southern/soul        1
fast food            1
chicken              1
french ( new )       1
middle eastern       1
indonesian           1
american ( new )     1
health food          1
vietnamese           1
mexican/tex-mex      1
steakhouses          1
russian              1
cajun/creole         1
japanese             1
pizza                1
Name: count, dtype: int64

In [102]:
from thefuzz import process
import numpy as np
choices = ['american','italian','asian']

def get_clean_type(dirty_type, choices, threshold=80):
    if dirty_type is None:
        return np.NaN
    if len(dirty_type) == 0:
        return np.NaN
    if len(choices) == 0:
        return np.NaN

    result = process.extractOne(dirty_type, choices=choices)
    #print(result)
    if result[1]<=threshold:
        return np.NaN
    else:
        return result[0]
    

df['type_clean'] = df['type'].apply(get_clean_type, choices=choices)

df

,name,addr,city,phone,type,type_clean
0,kokomo,6333 w. third st.,la,2139330773,american,american
1,feenix,8358 sunset blvd. west,hollywood,2138486677,american,american
2,parkway,510 s. arroyo pkwy .,pasadena,8187951001,californian,NaN
3,r-23,923 e. third st.,los angeles,2136877178,japanese,NaN
4,gumbo,6333 w. third st.,la,2139330358,cajun/creole,NaN
...,...,...,...,...,...,...
77,feast,1949 westwood blvd.,west la,3104750400,chinese,NaN
78,mulberry,17040 ventura blvd.,encino,8189068881,pizza,NaN
79,matsuhissa,129 n. la cienega blvd.,beverly hills,3106599639,asian,asian
80,jiraffe,502 santa monica blvd,santa monica,3109176671,californian,NaN
81,martha's,22nd street grill 25 22nd,st. hermosa beach,3103767786,american,american

In [94]:
df['type'].value_counts(dropna=False)

type
american            20
italian              7
californian          5
coffee shops         5
asian                4
hot dogs             3
diners               3
delis                3
hamburgers           3
mexican              3
noodle shops         2
pacific new wave     2
seafood              2
continental          1
coffeebar            1
eclectic             1
desserts             1
chinese              1
southern/soul        1
fast food            1
chicken              1
french ( new )       1
middle eastern       1
indonesian           1
american ( new )     1
health food          1
vietnamese           1
mexican/tex-mex      1
steakhouses          1
russian              1
cajun/creole         1
japanese             1
pizza                1
Name: count, dtype: int64

In [76]:
scores = process.extractOne('heloo',['hola','hell', 'iran','hello'])
scores#[0][0]

('hello', 80)

In [103]:
df.dtypes

name          object
addr          object
city          object
phone          int64
type          object
type_clean    object
dtype: object

In [113]:
print(file_names)
df = pd.read_csv(path+'/'+file_names[-1], index_col=0)
print(df.dtypes)
df

['restaurants_L2_dirty.csv', 'restaurants_L2.csv', 'banking_dirty (1).csv', 'airlines_final.csv', 'ride_sharing_new.csv', 'banking_dirty.csv']
cust_id              object
birth_date           object
Age                   int64
acct_amount         float64
inv_amount            int64
fund_A              float64
fund_B              float64
fund_C              float64
fund_D              float64
account_opened       object
last_transaction     object
dtype: object

,cust_id,birth_date,Age,acct_amount,inv_amount,fund_A,fund_B,fund_C,fund_D,account_opened,last_transaction
0,870A9281,1962-06-09,58,63523.31,51295,30105.0,4138.0,1420.0,15632.0,02-09-18,22-02-19
1,166B05B0,1962-12-16,58,38175.46,15050,4995.0,938.0,6696.0,2421.0,28-02-19,31-10-18
2,BFC13E88,1990-09-12,34,59863.77,24567,10323.0,4590.0,8469.0,1185.0,25-04-18,02-04-18
3,F2158F66,1985-11-03,35,84132.10,23712,3908.0,492.0,6482.0,12830.0,07-11-17,08-11-18
4,7A73F334,1990-05-17,30,120512.00,93230,12158.4,51281.0,13434.0,18383.0,14-05-18,19-07-18
...,...,...,...,...,...,...,...,...,...,...,...
95,CA507BA1,1974-08-10,46,12209.84,7515,190.0,931.0,1451.0,4943.0,26-05-18,11-09-19
96,B99CD662,1989-12-12,31,92838.44,49089,2453.0,7892.0,31486.0,7258.0,04-05-17,12-03-19
97,13770971,1984-11-29,36,92750.87,27962,3352.0,7547.0,8486.0,8577.0,16-08-17,24-04-19
98,93E78DA3,1969-12-14,51,41942.23,29662,1758.0,11174.0,11650.0,5080.0,09-10-17,15-04-18
99,AC91D689,1993-05-18,27,99490.61,32149,2184.0,17918.0,6714.0,5333.0,01-08-17,04-08-19