In [2]:
import numpy as np
import pandas as pd

In [3]:
heroes = ['A-Bomb', 'Abe Sapien', 'Abin Sur', 'Abomination', 'Absorbing Man', 'Adam Strange', 'Agent 13', 'Agent Bob', 'Agent Zero', 'Air-Walker', 'Ajax', 'Alan Scott', 'Alfred Pennyworth', 'Alien', 'Amazo', 'Ammo', 'Angel', 'Angel Dust', 'Angel Salvadore', 'Animal Man', 'Annihilus', 'Ant-Man', 'Ant-Man II', 'Anti-Venom', 'Apocalypse', 'Aqualad', 'Aquaman', 'Arachne', 'Archangel', 'Arclight', 'Ardina', 'Ares', 'Ariel', 'Armor', 'Atlas', 'Atom', 'Atom Girl', 'Atom II', 'Aurora', 'Azazel', 'Bane', 'Banshee', 'Bantam', 'Batgirl', 'Batgirl IV', 'Batgirl VI', 'Batman', 'Batman II', 'Battlestar', 'Beak', 'Beast', 'Beast Boy', 'Beta Ray Bill', 'Big Barda', 'Big Man', 'Binary', 'Bishop', 'Bizarro', 'Black Adam', 'Black Bolt', 'Black Canary', 'Black Cat', 'Black Knight III', 'Black Lightning', 'Black Mamba', 'Black Manta', 'Black Panther', 'Black Widow', 'Black Widow II', 'Blackout', 'Blackwing', 'Blackwulf', 'Blade', 'Bling!', 'Blink', 'Blizzard II', 'Blob', 'Bloodaxe', 'Blue Beetle II', 'Boom-Boom', 'Booster Gold', 'Box III', 'Brainiac', 'Brainiac 5', 'Brother Voodoo', 'Buffy', 'Bullseye', 'Bumblebee', 'Cable', 'Callisto', 'Cannonball', 'Captain America', 'Captain Atom', 'Captain Britain', 'Captain Mar-vell', 'Captain Marvel', 'Captain Marvel II', 'Carnage', 'Cat', 'Catwoman', 'Cecilia Reyes', 'Century', 'Chamber', 'Changeling', 'Cheetah', 'Cheetah II', 'Cheetah III', 'Chromos', 'Citizen Steel', 'Cloak', 'Clock King', 'Colossus', 'Copycat', 'Corsair', 'Cottonmouth', 'Crimson Dynamo', 'Crystal', 'Cyborg', 'Cyclops', 'Cypher', 'Dagger', 'Daredevil', 'Darkhawk', 'Darkseid', 'Darkstar', 'Darth Vader', 'Dash', 'Dazzler', 'Deadman', 'Deadpool', 'Deadshot', 'Deathlok', 'Deathstroke', 'Demogoblin', 'Destroyer', 'Diamondback', 'Doc Samson', 'Doctor Doom', 'Doctor Doom II', 'Doctor Fate', 'Doctor Octopus', 'Doctor Strange', 'Domino', 'Donna Troy', 'Doomsday', 'Doppelganger', 'Drax the Destroyer', 'Elastigirl', 'Electro', 'Elektra', 'Elongated Man', 'Emma Frost', 'Enchantress', 'Etrigan', 'Evil Deadpool', 'Evilhawk', 'Exodus', 'Fabian Cortez', 'Falcon', 'Feral', 'Fin Fang Foom', 'Firebird', 'Firelord', 'Firestar', 'Firestorm', 'Flash', 'Flash II', 'Flash III', 'Flash IV', 'Forge', 'Franklin Richards', 'Franklin Storm', 'Frenzy', 'Frigga', 'Galactus', 'Gambit', 'Gamora', 'Genesis', 'Ghost Rider', 'Giganta', 'Gladiator', 'Goblin Queen', 'Goku', 'Goliath IV', 'Gorilla Grodd', 'Granny Goodness', 'Gravity', 'Green Arrow', 'Green Goblin', 'Green Goblin II', 'Green Goblin III', 'Green Goblin IV', 'Groot', 'Guy Gardner', 'Hal Jordan', 'Han Solo', 'Harley Quinn', 'Havok', 'Hawk', 'Hawkeye', 'Hawkeye II', 'Hawkgirl', 'Hawkman', 'Hawkwoman', 'Hawkwoman III', 'Heat Wave', 'Hela', 'Hellboy', 'Hellcat', 'Hellstorm', 'Hercules', 'Hobgoblin', 'Hope Summers', 'Howard the Duck', 'Hulk', 'Human Torch', 'Huntress', 'Husk', 'Hybrid', 'Hydro-Man', 'Hyperion', 'Iceman', 'Impulse', 'Ink', 'Invisible Woman', 'Iron Fist', 'Iron Man', 'Jack of Hearts', 'Jack-Jack', 'James T. Kirk', 'Jean Grey', 'Jennifer Kale', 'Jessica Jones', 'Jigsaw', 'John Stewart', 'John Wraith', 'Joker', 'Jolt', 'Jubilee', 'Juggernaut', 'Justice', 'Kang', 'Karate Kid', 'Killer Croc', 'Kilowog', 'Kingpin', 'Klaw', 'Kraven II', 'Kraven the Hunter', 'Krypto', 'Kyle Rayner', 'Lady Deathstrike', 'Leader', 'Legion', 'Lex Luthor', 'Light Lass', 'Lightning Lad', 'Lightning Lord', 'Living Brain', 'Lizard', 'Lobo', 'Loki', 'Longshot', 'Luke Cage', 'Luke Skywalker', 'Mach-IV', 'Machine Man', 'Magneto', 'Man-Thing', 'Man-Wolf', 'Mandarin', 'Mantis', 'Martian Manhunter', 'Marvel Girl', 'Master Brood', 'Maverick', 'Maxima', 'Medusa', 'Meltdown', 'Mephisto', 'Mera', 'Metallo', 'Metamorpho', 'Metron', 'Micro Lad', 'Mimic', 'Miss Martian', 'Mister Fantastic', 'Mister Freeze', 'Mister Sinister', 'Mockingbird', 'MODOK', 'Molten Man', 'Monarch', 'Moon Knight', 'Moonstone', 'Morlun', 'Morph', 'Moses Magnum', 'Mr Immortal', 'Mr Incredible', 'Ms Marvel II', 'Multiple Man', 'Mysterio', 'Mystique', 'Namor', 'Namora', 'Namorita', 'Naruto Uzumaki', 'Nebula', 'Nick Fury', 'Nightcrawler', 'Nightwing', 'Northstar', 'Nova', 'Odin', 'Omega Red', 'Omniscient', 'One Punch Man', 'Onslaught', 'Oracle', 'Paul Blart', 'Penance II', 'Penguin', 'Phantom Girl', 'Phoenix', 'Plantman', 'Plastic Man', 'Plastique', 'Poison Ivy', 'Polaris', 'Power Girl', 'Predator', 'Professor X', 'Professor Zoom', 'Psylocke', 'Punisher', 'Purple Man', 'Pyro', 'Question', 'Quicksilver', 'Quill', "Ra's Al Ghul", 'Raven', 'Ray', 'Razor-Fist II', 'Red Arrow', 'Red Hood', 'Red Hulk', 'Red Robin', 'Red Skull', 'Red Tornado', 'Rhino', 'Rick Flag', 'Ripcord', 'Robin', 'Robin II', 'Robin III', 'Robin V', 'Rocket Raccoon', 'Rogue', 'Ronin', 'Rorschach', 'Sabretooth', 'Sage', 'Sandman', 'Sasquatch', 'Scarecrow', 'Scarlet Spider', 'Scarlet Spider II', 'Scarlet Witch', 'Scorpion', 'Sentry', 'Shadow King', 'Shadow Lass', 'Shadowcat', 'Shang-Chi', 'Shatterstar', 'She-Hulk', 'She-Thing', 'Shocker', 'Shriek', 'Sif', 'Silver Surfer', 'Silverclaw', 'Sinestro', 'Siren', 'Siryn', 'Skaar', 'Snowbird', 'Solomon Grundy', 'Songbird', 'Space Ghost', 'Spawn', 'Spider-Girl', 'Spider-Gwen', 'Spider-Man', 'Spider-Woman', 'Spider-Woman III', 'Spider-Woman IV', 'Spock', 'Spyke', 'Star-Lord', 'Starfire', 'Stargirl', 'Static', 'Steel', 'Steppenwolf', 'Storm', 'Sunspot', 'Superboy', 'Superboy-Prime', 'Supergirl', 'Superman', 'Swarm', 'Synch', 'T-1000', 'Taskmaster', 'Tempest', 'Thanos', 'The Comedian', 'Thing', 'Thor', 'Thor Girl', 'Thunderbird', 'Thunderbird III', 'Thunderstrike', 'Thundra', 'Tiger Shark', 'Tigra', 'Tinkerer', 'Toad', 'Toxin', 'Trickster', 'Triplicate Girl', 'Triton', 'Two-Face', 'Ultragirl', 'Ultron', 'Utgard-Loki', 'Vagabond', 'Valerie Hart', 'Valkyrie', 'Vanisher', 'Vegeta', 'Venom', 'Venom II', 'Venom III', 'Vertigo II', 'Vibe', 'Vindicator', 'Violet Parr', 'Vision', 'Vision II', 'Vixen', 'Vulture', 'Walrus', 'War Machine', 'Warbird', 'Warlock', 'Warp', 'Warpath', 'Wasp', 'White Queen', 'Winter Soldier', 'Wiz Kid', 'Wolfsbane', 'Wolverine', 'Wonder Girl', 'Wonder Man', 'Wonder Woman', 'Wyatt Wingfoot', 'X-23', 'X-Man', 'Yellow Claw', 'Yellowjacket', 'Yellowjacket II', 'Yoda', 'Zatanna', 'Zoom']
hts = np.array([
    203. , 191. , 185. , 203. , 193. , 185. , 173. , 178. , 191. , 188. , 193. , 180.,
    178. , 244. , 257. , 188. , 183. , 165. , 163. , 183. , 180. , 211. , 183. , 229.,
    213. , 178. , 185. , 175. , 183. , 173. , 193. , 185. , 165. , 163. , 183. , 178.,
    168. , 183. , 180. , 183. , 203. , 183. , 165. , 170. , 165. , 168. , 188. , 178.,
    198. , 175. , 180. , 173. , 201. , 188. , 165. , 180. , 198. , 191. , 191. , 188.,
    165. , 178. , 183. , 185. , 170. , 188. , 183. , 170. , 170. , 191. , 185. , 188.,
    188. , 168. , 165. , 175. , 178. , 218. , 183. , 165. , 196. , 193. , 198. , 170.,
    183. , 157. , 183. , 170. , 203. , 175. , 183. , 188. , 193. , 198. , 188. , 180.,
    175. , 185. , 173. , 175. , 170. , 201. , 175. , 180. , 163. , 170. , 175. , 185.,
    183. , 226. , 178. , 226. , 183. , 191. , 183. , 180. , 168. , 198. , 191. , 175.,
    165. , 183. , 185. , 267. , 168. , 198. , 122. , 173. , 183. , 188. , 185. , 193.,
    193. , 185. , 188. , 193. , 198. , 201. , 201. , 188. , 175. , 188. , 173. , 175.,
    244. , 196. , 193. , 168. , 180. , 175. , 185. , 178. , 168. , 193. , 188. , 191.,
    183. , 196. , 188. , 175. , 975. , 165. , 193. , 173. , 188. , 180. , 183. , 183.,
    157. , 183. , 142. , 188. , 211. , 180. , 876. , 185. , 183. , 185. , 188. ,  62.5,
    198. , 168. , 175. , 183. , 198. , 178. , 178. , 188. , 180. , 178. , 183. , 178.,
    701. , 188. , 188. , 183. , 170. , 183. , 185. , 191. , 165. , 175. , 185. , 175.,
    170. , 180. , 213. , 259. , 173. , 185. , 196. , 180. , 168. ,  79. , 244. , 178.,
    180. , 170. , 175. , 188. , 183. , 173. , 170. , 180. , 168. , 180. , 198. , 155.,
    71. , 178. , 168.  ,168.  ,170.  ,188.  ,185.  ,183.  ,196. , 165. , 165.  ,287.,
    178. , 191. , 173. , 244. , 234. , 201. , 188. , 191. , 183. ,  64. , 180. , 175.,
    178. , 175. , 188. , 165. , 155. , 191. , 198. , 203. , 229. , 193. , 188. , 198.,
    168. , 180. , 183. , 188. , 213. , 188. , 188. , 168. , 201. , 170. , 183. , 193.,
    180. , 180. , 165. , 198. , 175. , 196. , 185. , 185. , 183. , 188. , 178. , 185.,
    183. , 196. , 175. , 366. , 196. , 193. , 188. , 180. , 188. , 178. , 175. , 188.,
    201. , 173. , 180. , 180. , 178. , 188. , 180. , 168. , 168. , 185. , 185. , 175.,
    178. , 180. , 185. , 206. , 211. , 180. , 175. , 305. , 178. , 170. , 183. , 157.,
    168. , 168. , 183. , 185. , 168. , 168. , 170. , 180. , 213. , 183. , 180. , 180.,
    183. , 180. , 178. , 188. , 183. , 163. , 193. , 165. , 178. , 191. , 180. , 183.,
    213. , 165. , 188. , 185. , 196. , 185. , 180. , 178. , 183. , 165. , 137. , 122.,
    173. , 191. , 168. , 198. , 170. , 185. , 305. , 183. , 178. , 193. , 170. , 211.,
    188. , 185. , 173. , 168. , 178. , 191. , 201. , 183. , 175. , 173. , 188. , 193.,
    157. , 201. , 175. , 168. , 198. , 178. , 279. , 165. , 188. , 211. , 170. , 165.,
    178. , 178. , 173. , 178. , 185. , 183. , 188. , 193. , 165. , 170. , 201. , 183.,
    180. , 173. , 170. , 180. , 165. , 191. , 196. , 180. , 183. , 188. , 163. , 201.,
    188. , 183. , 198. , 175. , 185. , 175. , 198. , 218. , 185. , 178. , 163. , 175.,
    188. , 183. , 168. , 188. , 183. , 168. , 206. ,  15.2 ,168. , 175. , 191. , 165.,
    168. , 191. , 175. , 229. , 168. , 178. , 165. , 137.  ,191. , 191. , 175. , 180.,
    183. , 185. , 180. , 188. , 173. , 218. , 163. , 178.  ,175. , 140. , 366. , 160.,
    165. , 188. , 183. , 196. , 155. , 175. , 188. , 183.  ,165.  , 66. , 170. , 185. ])

wts = np.array([
    203. , 191. , 185. , 203. , 193. , 185. , 173. , 178. , 191. , 188. , 193. , 180.,
    178. , 244. , 257. , 188. , 183. , 165. , 163. , 183. , 180. , 211. , 183. , 229.,
    213. , 178. , 185. , 175. , 183. , 173. , 193. , 185. , 165. , 163. , 183. , 178.,
    168. , 183. , 180. , 183. , 203. , 183. , 165. , 170. , 165. , 168. , 188. , 178.,
    198. , 175. , 180. , 173. , 201. , 188. , 165. , 180. , 198. , 191. , 191. , 188.,
    165. , 178. , 183. , 185. , 170. , 188. , 183. , 170. , 170. , 191. , 185. , 188.,
    188. , 168. , 165. , 175. , 178. , 218. , 183. , 165. , 196. , 193. , 198. , 170.,
    183. , 157. , 183. , 170. , 203. , 175. , 183. , 188. , 193. , 198. , 188. , 180.,
    175. , 185. , 173. , 175. , 170. , 201. , 175. , 180. , 163. , 170. , 175. , 185.,
    183. , 226. , 178. , 226. , 183. , 191. , 183. , 180. , 168. , 198. , 191. , 175.,
    165. , 183. , 185. , 267. , 168. , 198. , 122. , 173. , 183. , 188. , 185. , 193.,
    193. , 185. , 188. , 193. , 198. , 201. , 201. , 188. , 175. , 188. , 173. , 175.,
    244. , 196. , 193. , 168. , 180. , 175. , 185. , 178. , 168. , 193. , 188. , 191.,
    183. , 196. , 188. , 175. , 975. , 165. , 193. , 173. , 188. , 180. , 183. , 183.,
    157. , 183. , 142. , 188. , 211. , 180. , 876. , 185. , 183. , 185. , 188. ,  62.5,
    198. , 168. , 175. , 183. , 198. , 178. , 178. , 188. , 180. , 178. , 183. , 178.,
    701. , 188. , 188. , 183. , 170. , 183. , 185. , 191. , 165. , 175. , 185. , 175.,
    170. , 180. , 213. , 259. , 173. , 185. , 196. , 180. , 168. ,  79. , 244. , 178.,
    180. , 170. , 175. , 188. , 183. , 173. , 170. , 180. , 168. , 180. , 198. , 155.,
    71. , 178. , 168.  ,168.  ,170.  ,188.  ,185.  ,183.  ,196. , 165. , 165.  ,287.,
    178. , 191. , 173. , 244. , 234. , 201. , 188. , 191. , 183. ,  64. , 180. , 175.,
    178. , 175. , 188. , 165. , 155. , 191. , 198. , 203. , 229. , 193. , 188. , 198.,
    168. , 180. , 183. , 188. , 213. , 188. , 188. , 168. , 201. , 170. , 183. , 193.,
    180. , 180. , 165. , 198. , 175. , 196. , 185. , 185. , 183. , 188. , 178. , 185.,
    183. , 196. , 175. , 366. , 196. , 193. , 188. , 180. , 188. , 178. , 175. , 188.,
    201. , 173. , 180. , 180. , 178. , 188. , 180. , 168. , 168. , 185. , 185. , 175.,
    178. , 180. , 185. , 206. , 211. , 180. , 175. , 305. , 178. , 170. , 183. , 157.,
    168. , 168. , 183. , 185. , 168. , 168. , 170. , 180. , 213. , 183. , 180. , 180.,
    183. , 180. , 178. , 188. , 183. , 163. , 193. , 165. , 178. , 191. , 180. , 183.,
    213. , 165. , 188. , 185. , 196. , 185. , 180. , 178. , 183. , 165. , 137. , 122.,
    173. , 191. , 168. , 198. , 170. , 185. , 305. , 183. , 178. , 193. , 170. , 211.,
    188. , 185. , 173. , 168. , 178. , 191. , 201. , 183. , 175. , 173. , 188. , 193.,
    157. , 201. , 175. , 168. , 198. , 178. , 279. , 165. , 188. , 211. , 170. , 165.,
    178. , 178. , 173. , 178. , 185. , 183. , 188. , 193. , 165. , 170. , 201. , 183.,
    180. , 173. , 170. , 180. , 165. , 191. , 196. , 180. , 183. , 188. , 163. , 201.,
    188. , 183. , 198. , 175. , 185. , 175. , 198. , 218. , 185. , 178. , 163. , 175.,
    188. , 183. , 168. , 188. , 183. , 168. , 206. ,  15.2 ,168. , 175. , 191. , 165.,
    168. , 191. , 175. , 229. , 168. , 178. , 165. , 137.  ,191. , 191. , 175. , 180.,
    183. , 185. , 180. , 188. , 173. , 218. , 163. , 178.  ,175. , 140. , 366. , 160.,
    165. , 188. , 183. , 196. , 155. , 175. , 188. , 183.  ,165.  , 66. , 170. , 185. ])

In [29]:
zipper = zip(heroes,hts.tolist(),wts.tolist())
mapp = map(list,zipper)
df = pd.DataFrame([*mapp],columns=['Nombre','height','wieght'])
df.to_csv('c:/Users/HN34064/Downloads/DevSec/heroes.csv', index=False)

In [41]:
from datetime import datetime 
now = datetime.now()
df['datetime'] = now
df.head()

          Nombre  height  wieght                   datetime
0         A-Bomb   203.0   203.0 2026-05-05 11:43:58.616529
1     Abe Sapien   191.0   191.0 2026-05-05 11:43:58.616529
2       Abin Sur   185.0   185.0 2026-05-05 11:43:58.616529
3    Abomination   203.0   203.0 2026-05-05 11:43:58.616529
4  Absorbing Man   193.0   193.0 2026-05-05 11:43:58.616529

In [43]:
df.to_parquet('c:\\Users\\HN34064\\Downloads\\DevSec\\heroes.parquet', index=False, compression='snappy')

In [35]:
import os
os.chdir(path='c:\\Users\\HN34064\\Downloads\\DevSec')

In [37]:
os.getcwd()

'c:\\Users\\HN34064\\Downloads\\DevSec'

In [ ]:
os.path.exists('c:\\Users\\HN34064\\Downloads\\DevSec')

False

In [33]:
help(os.chdir)

Help on built-in function chdir in module nt:

chdir(path)
    Change the current working directory to the specified path.

    path may always be specified as a string.
    On some platforms, path may also be specified as an open file descriptor.
      If this functionality is unavailable, using it raises an exception.

In [32]:
dir(os)

['DirEntry',
 'EX_OK',
 'F_OK',
 'GenericAlias',
 'Mapping',
 'MutableMapping',
 'O_APPEND',
 'O_BINARY',
 'O_CREAT',
 'O_EXCL',
 'O_NOINHERIT',
 'O_RANDOM',
 'O_RDONLY',
 'O_RDWR',
 'O_SEQUENTIAL',
 'O_SHORT_LIVED',
 'O_TEMPORARY',
 'O_TEXT',
 'O_TRUNC',
 'O_WRONLY',
 'P_DETACH',
 'P_NOWAIT',
 'P_NOWAITO',
 'P_OVERLAY',
 'P_WAIT',
 'PathLike',
 'R_OK',
 'SEEK_CUR',
 'SEEK_END',
 'SEEK_SET',
 'TMP_MAX',
 'W_OK',
 'X_OK',
 '_AddedDllDirectory',
 '_Environ',
 '__all__',
 '__builtins__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_check_methods',
 '_execvpe',
 '_exists',
 '_exit',
 '_fspath',
 '_get_exports_list',
 '_walk_symlinks_as_files',
 '_wrap_close',
 'abc',
 'abort',
 'access',
 'add_dll_directory',
 'altsep',
 'chdir',
 'chmod',
 'close',
 'closerange',
 'cpu_count',
 'curdir',
 'defpath',
 'device_encoding',
 'devnull',
 'dup',
 'dup2',
 'environ',
 'error',
 'execl',
 'execle',
 'execlp',
 'execlpe',
 'execv',
 'execve',
 'execvp',
 'execvpe',
 'extsep',
 'fdopen',
 'fsdecode',
 'fsencode',
 'fspath',
 'fstat',
 'fsync',
 'ftruncate',
 'get_blocking',
 'get_exec_path',
 'get_handle_inheritable',
 'get_inheritable',
 'get_terminal_size',
 'getcwd',
 'getcwdb',
 'getenv',
 'getlogin',
 'getpid',
 'getppid',
 'isatty',
 'kill',
 'linesep',
 'link',
 'listdir',
 'listdrives',
 'listmounts',
 'listvolumes',
 'lseek',
 'lstat',
 'makedirs',
 'mkdir',
 'name',
 'open',
 'pardir',
 'path',
 'pathsep',
 'pipe',
 'popen',
 'putenv',
 'read',
 'readlink',
 'remove',
 'removedirs',
 'rename',
 'renames',
 'replace',
 'rmdir',
 'scandir',
 'sep',
 'set_blocking',
 'set_handle_inheritable',
 'set_inheritable',
 'spawnl',
 'spawnle',
 'spawnv',
 'spawnve',
 'st',
 'startfile',
 'stat',
 'stat_result',
 'statvfs_result',
 'strerror',
 'supports_bytes_environ',
 'supports_dir_fd',
 'supports_effective_ids',
 'supports_fd',
 'supports_follow_symlinks',
 'symlink',
 'sys',
 'system',
 'terminal_size',
 'times',
 'times_result',
 'truncate',
 'umask',
 'uname_result',
 'unlink',
 'unsetenv',
 'urandom',
 'utime',
 'waitpid',
 'waitstatus_to_exitcode',
 'walk',
 'write']

In [ ]:
wts = (wts**2)/2.3
wts.sort()
wts = wts**0.5

In [ ]:
raw_df = pd.DataFrame([*zip(heroes,hts,wts)], columns=['nombre','altura','peso*'])

def get_second_char(val : str=None) -> str:
    if val == None:
        return ''
    if len(val) < 2:
        return ''

    return val[1:2]
   
raw_df['segunda_letra'] = raw_df['nombre'].apply(get_second_char)
tmp = raw_df.groupby(by=['segunda_letra']).size()#.reset_index(name='conteo')
values = tmp.index.to_list()
counts = tmp.values.tolist()

#counts_dict = {k:v for k,v in zip(values,counts)}
counts_dict = dict(zip(values, counts))

raw_df['segunda_letra_counter'] = raw_df['segunda_letra'].map(counts_dict)

#raw_df.groupby(by=['segunda_letra'])['segunda_letra_counter'].agg(['size','mean','sum']).reset_index()

raw_df.groupby(by=['segunda_letra']).agg(conteo=('segunda_letra','size'),
                                            promedio=('segunda_letra_counter','mean'),
                                            suman=('segunda_letra_counter','sum')).reset_index()

   segunda_letra  conteo  promedio  suman
0              -       4       4.0     16
1              O       1       1.0      1
2              a      89      89.0   7921
3              b       4       4.0     16
4              c       6       6.0     36
5              d       2       2.0      4
6              e      53      53.0   2809
7              g       3       3.0      9
8              h      29      29.0    841
9              i      51      51.0   2601
10             j       1       1.0      1
11             k       1       1.0      1
12             l      41      41.0   1681
13             m       6       6.0     36
14             n      14      14.0    196
15             o      64      64.0   4096
16             p      11      11.0    121
17             q       2       2.0      4
18             r      39      39.0   1521
19             s       2       2.0      4
20             t      13      13.0    169
21             u      26      26.0    676
22             v       2       2.0      4
23             w       2       2.0      4
24             x       1       1.0      1
25             y      12      12.0    144
26             z       1       1.0      1

In [105]:
help(zip)

Help on class zip in module builtins:

class zip(object)
 |  zip(*iterables, strict=False) --> Yield tuples until an input is exhausted.
 |
 |     >>> list(zip('abcdefg', range(3), range(4)))
 |     [('a', 0, 0), ('b', 1, 1), ('c', 2, 2)]
 |
 |  The zip object yields n-length tuples, where n is the number of iterables
 |  passed as positional arguments to zip().  The i-th element in every tuple
 |  comes from the i-th iterable argument to zip().  This continues until the
 |  shortest argument is exhausted.
 |
 |  If strict is true and one of the arguments is exhausted before the others,
 |  raise a ValueError.
 |
 |  Methods defined here:
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __next__(self, /)
 |      Implement next(self).
 |
 |  __reduce__(...)
 |      Return state information for pickling.
 |
 |  __setstate__(...)
 |      Set state information for unpickling.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs)
 |      Create and return a new object.  See help(type) for accurate signature.

In [ ]:
from collections import Counter
tmp = map(lambda x: x[0],heroes)
Counter(tmp)

Counter({'S': 53,
         'B': 48,
         'A': 40,
         'M': 40,
         'C': 32,
         'D': 27,
         'H': 27,
         'R': 21,
         'T': 21,
         'G': 20,
         'P': 18,
         'F': 17,
         'V': 16,
         'W': 16,
         'J': 14,
         'L': 14,
         'E': 10,
         'K': 10,
         'N': 10,
         'I': 6,
         'O': 6,
         'Y': 4,
         'Q': 3,
         'U': 3,
         'X': 2,
         'Z': 2})

In [40]:
raw_df

              nombre  altura       peso*
0             A-Bomb   203.0   10.022583
1         Abe Sapien   191.0   41.211280
2           Abin Sur   185.0   42.200350
3        Abomination   203.0   43.519111
4      Absorbing Man   193.0   46.816014
..               ...     ...         ...
475     Yellowjacket   183.0  241.333253
476  Yellowjacket II   165.0  241.333253
477             Yoda    66.0  462.225712
478          Zatanna   170.0  577.617295
479             Zoom   185.0  642.895962

[480 rows x 3 columns]